steps:

  - id: "Executando docker-compose"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.yaml', 'up', '-d' ]

  - id: "Permissão em www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www' ]

  - id: "Executando composer"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: "Copiando .env"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'cp', '/var/www/.env.example', '/var/www/.env' ]

  - id: "Copiando .env.testing"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'cp', '/var/www/.env.testing.example', '/var/www/.env.testing' ]

  - id: "Executando key:generate"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate' ]

  - id: "Executando migrations"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate' ]

  - id: "Executando phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
