steps:

  - id: 'Gerando service-account-storage.json'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=./storage/credentials/google/service-account-storage.json.enc
      - --plaintext-file=./storage/credentials/google/service-account-storage.json
      - --location=global
      - --keyring=testing
      - --key=service-account

  - id: "Executando docker-compose"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.yaml', 'up', '-d' ]
    env:
      - GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_KEY_FILE=service-account-storage.json
      - GOOGLE_CLOUD_STORAGE_BUCKET=code-micro-videos-rrc
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/code_micro_videos-rrc
      - TESTING_PROD=true

  - id: "Permissão em www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www' ]

  - id: "Executando composer"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'composer', 'install' ]

  - id: "Copiando .env"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'cp', '/var/www/.env.example', '/var/www/.env' ]

  - id: "Copiando .env.testing"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'cp', '/var/www/.env.testing.example', '/var/www/.env.testing' ]

  - id: "Executando key:generate"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate' ]

  - id: "Executando migrations"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate' ]

  - id: "Executando phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
